import Head from 'next/head'
import { useState } from 'react';

export default function Home() {

  const [timeNow, setTimeNow] = useState(new Date().toString());

  setInterval(() => {
    setTimeNow(new Date().toString())
  }, 1000);

  return (
    <div className="">
      <Head>
        <title>Serverless</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ padding: '2rem' }}>
        <h1>Serverless on AWS</h1>
        <p>Time now: {timeNow}</p>
        <p>Build time: {process.env.BUILD_TIME}</p>
        <p>Environment: {process.env.ENVIRONMENT}</p>
      </div>
    </div>
  )
}
