name: Deploy INT to AWS Lambda

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: int
      url: https://d3h06pp9i9ga0d.cloudfront.net/
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Yarn dependencies
        run: yarn install
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Download `.serverless` state from S3
        run: aws s3 sync s3://nextjs-serverless-state/int/.serverless .serverless --delete
      - name: Deploy to AWS
        run: rm -f serverless.yml && cp serverless_int.yml serverless.yml && yarn serverless
        env:
          ENVIRONMENT: int
      - name: Upload `.serverless` state to S3
        run: aws s3 sync .serverless s3://nextjs-serverless-state/int/.serverless --delete
