name: Deploy TEST to AWS Lambda

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: test
      url: https://d2iuy9cgwg671a.cloudfront.net/
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Yarn dependencies
        run: yarn install
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Download `.serverless` state from S3
        run: aws s3 sync s3://nextjs-serverless-state/test/.serverless .serverless --delete
      - name: Deploy to AWS
        run: rm -f serverless.yml && cp serverless_test.yml serverless.yml && yarn serverless
        env:
          ENVIRONMENT: test
      - name: Upload `.serverless` state to S3
        run: aws s3 sync .serverless s3://nextjs-serverless-state/test/.serverless --delete
